/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        // TradeSmith design tokens from Stitch
        primary: "#8d4b00",
        "on-primary": "#ffffff",
        "primary-container": "#b15f00",
        "on-primary-container": "#fffbff",
        "inverse-primary": "#ffb77d",
        secondary: "#515f74",
        "on-secondary": "#ffffff",
        "secondary-container": "#d5e3fd",
        "on-secondary-container": "#57657b",
        tertiary: "#006096",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#007abd",
        background: "#fff8f5",
        "on-background": "#231a13",
        surface: "#fff8f5",
        "on-surface": "#231a13",
        "surface-variant": "#f2dfd3",
        "on-surface-variant": "#554336",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#fff1e9",
        "surface-container": "#fdeade",
        "surface-container-high": "#f7e5d9",
        "surface-container-highest": "#f2dfd3",
        "surface-bright": "#fff8f5",
        "surface-dim": "#e9d7cb",
        "inverse-surface": "#392e26",
        "inverse-on-surface": "#ffede3",
        outline: "#887364",
        "outline-variant": "#dbc2b0",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#ffdcc3",
        "primary-fixed-dim": "#ffb77d",
        "on-primary-fixed": "#2f1500",
        "on-primary-fixed-variant": "#6e3900",
      },
      fontFamily: {
        sans: ["Inter_400Regular"],
        "sans-medium": ["Inter_500Medium"],
        "sans-semibold": ["Inter_600SemiBold"],
        mono: ["JetBrainsMono_400Regular"],
      },
      borderRadius: {
        DEFAULT: "8px",
      },
    },
  },
  plugins: [],
};
